[package]
name = "manuscript_generator"
version = "0.1.0"
edition = "2021"
description = "Compile spans and analyses into scientific manuscripts"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
md5 = { workspace = true }
